import { Student, ModelTestResult, Course } from "./types";

export const COURSES: Course[] = [
  {
    id: "office-app",
    title: "Computer Office Application",
    bengliTitle: "কম্পিউটার অফিস অ্যাপ্লিকেশন (MS Word, Excel, PowerPoint, Access)",
    duration: "3 Months / 6 Months",
    fee: 4500,
    icon: "Monitor",
    skillsCovered: [
      "Microsoft Word (Documentation, Bangla Typing, Formatting)",
      "Microsoft Excel (Mathematical Calculations, Formatting, Charts)",
      "Microsoft PowerPoint (Presentations, Slide Animations, Transitions)",
      "Microsoft Access (Basic Database, Tables, Queries, Reports)",
      "Internet Browsing, Emailing, Government Job Circular Applications"
    ],
    schedule: "Sun, Tue, Thu (flexible batches)"
  },
  {
    id: "graphics-design",
    title: "Graphic Design & Multimedia",
    bengliTitle: "গ্রাফিক ডিজাইন ও মাল্টিমিডিয়া (Adobe Illustrator, Photoshop)",
    duration: "6 Months",
    fee: 8000,
    icon: "Palette",
    skillsCovered: [
      "Adobe Photoshop (Image Editing, Retouching, Photo Manipulation)",
      "Adobe Illustrator (Vector Design, Logo, Poster, Business Card)",
      "Bengali & English Typography (Bijoy Bayanno & Avro)",
      "Color Theory, Layout Design & Branding Concepts",
      "Freelancing Guidelines (Fiverr, Upwork, Freelancer)"
    ],
    schedule: "Mon, Wed, Sat"
  },
  {
    id: "web-dev",
    title: "Professional Web Development",
    bengliTitle: "প্রফেশনাল ওয়েব ডেভেলপমেন্ট (HTML, CSS, Tailwind, JS, React)",
    duration: "6 Months",
    fee: 12000,
    icon: "Code",
    skillsCovered: [
      "HTML5, CSS3, Modern Responsive Layouts",
      "Tailwind CSS Utility-First Styling Framework",
      "JavaScript Programming Fundamentals & DOM Manipulation",
      "React JS Component Architecture & Hooks",
      "Git & GitHub Version Control, Vercel & Netlify Deployment"
    ],
    schedule: "Mon, Wed, Fri (Evening Batch)"
  },
  {
    id: "database",
    title: "Database Programming & MS Access",
    bengliTitle: "ডেটাবেজ প্রোগ্রামিং অ্যান্ড ডিজাইন",
    duration: "3 Months",
    fee: 5500,
    icon: "Database",
    skillsCovered: [
      "Relational Database Management Systems (RDBMS)",
      "Microsoft Access Advanced forms, subforms, and SQL queries",
      "Excel VBA & Advanced Functions",
      "Data Normalization & Schema Planning",
      "Practical Office Office Billing System Projects"
    ],
    schedule: "Sun, Tue, Thu"
  }
];

export const INITIAL_STUDENTS: Student[] = [
  // Demo/Existing Students
  {
    roll: "1001",
    name: "Md Minhajul Kabir",
    fatherName: "Kabir Ahmed",
    motherName: "Minu Ara Begum",
    mobile: "01823901234",
    address: "Aman Bazar, Hathazari, Chittagong",
    course: "Computer Office Application",
    pin: "2021",
    regDate: "2026-01-10",
    pictureUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200&h=200",
    serialNo: 100
  },
  {
    roll: "1002",
    name: "Nur Islam Babo",
    fatherName: "Badiul Alam",
    motherName: "Fatema Begum",
    mobile: "01754123456",
    address: "Chowdhury Hat, Hathazari, Chittagong",
    course: "Computer Office Application",
    pin: "1994",
    regDate: "2026-01-12",
    pictureUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200&h=200",
    serialNo: 101
  },
  {
    roll: "1003",
    name: "Hamida Sultana",
    fatherName: "Mohiuddin Ahmed",
    motherName: "Sultana Razia",
    mobile: "01912345678",
    address: "Fatehpur, Hathazari, Chittagong",
    course: "Computer Office Application",
    pin: "1885",
    regDate: "2026-01-15",
    pictureUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200&h=200",
    serialNo: 102
  },
  {
    roll: "1004",
    name: "Rakibul Hassan",
    fatherName: "Abul Hashem",
    motherName: "Rehana Begum",
    mobile: "01684321098",
    address: "Katirhat, Hathazari, Chittagong",
    course: "Computer Office Application",
    pin: "3302",
    regDate: "2026-01-15",
    pictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200&h=200",
    serialNo: 103
  },
  {
    roll: "1005",
    name: "Suprity Shil",
    fatherName: "Niranjan Shil",
    motherName: "Sabita Shil",
    mobile: "01511223344",
    address: "Modunaghat, Hathazari, Chittagong",
    course: "Graphic Design & Multimedia",
    pin: "4050",
    regDate: "2026-01-18",
    pictureUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=200&h=200",
    serialNo: 104
  },
  // ... (keeping some others for variety, then adding the user's list)
  
  // User Provided Students (Roles 101-154)
  { "name": "Md Minhajul Kabir", "fatherName": "Humayoun Kabir", "motherName": "Sarbin Akter", "address": "Aman bazar", "mobile": "01752563250", "course": "Computer Office Application", "roll": "101", "pin": "2009", "regDate": "2026-06-10", "serialNo": 1 },
  { "name": "Nur Islam Babo", "fatherName": "Nasir Miya", "motherName": "Sahin Akter", "address": "Volioya para", "mobile": "01886515246", "course": "Computer Office Application", "roll": "102", "pin": "2007", "regDate": "2026-06-10", "serialNo": 2 },
  { "name": "Hamida Sulthana", "fatherName": "MD.Nasir", "motherName": "Kulsuma Aktar", "address": "Lalirhat", "mobile": "01830346676", "course": "Computer Office Application", "roll": "103", "pin": "2010", "regDate": "2026-06-10", "serialNo": 3 },
  { "name": "RAKIBUL Hassan", "fatherName": "Belal hossain", "motherName": "Rahima akter", "address": "Aman bazar", "mobile": "01872676210", "course": "Computer Office Application", "roll": "104", "pin": "2008", "regDate": "2026-06-10", "serialNo": 4 },
  { "name": "Suprity Shil", "fatherName": "Rakhal Shil", "motherName": "Ratna Shil", "address": "Khandakia", "mobile": "01996725194", "course": "Computer Office Application", "roll": "105", "pin": "2006", "regDate": "2026-06-10", "serialNo": 5 },
  { "name": "Tusha chowdhury", "fatherName": "Ajoy chowdhury", "motherName": "Arssna chowdhury", "address": "shikarpur", "mobile": "01585727018", "course": "Computer Office Application", "roll": "106", "pin": "2020", "regDate": "2026-06-10", "serialNo": 6 },
  { "name": "Jubayer Ivna", "fatherName": "Monsur Alam", "motherName": "Rubi Akter", "address": "Kulgaw", "mobile": "01860260834", "course": "Computer Office Application", "roll": "107", "pin": "1234", "regDate": "2026-06-10", "serialNo": 7 },
  { "name": "Shirin Akter", "fatherName": "Jane Alam", "motherName": "Parvin Akter", "address": "Kulgaw", "mobile": "01727718747", "course": "Computer Office Application", "roll": "108", "pin": "1234", "regDate": "2026-06-10", "serialNo": 8 },
  { "name": "Nusrat Alam", "fatherName": "Mohammed Khursed Alam", "motherName": "Shamim Akter", "address": "Khandakia", "mobile": "01885340870", "course": "Computer Office Application", "roll": "109", "pin": "1885", "regDate": "2026-06-10", "serialNo": 9 },
  { "name": "Emon", "fatherName": "Shahjhan", "motherName": "Feroza", "address": "Aman bazar", "mobile": "01642870994", "course": "Computer Office Application", "roll": "110", "pin": "1100", "regDate": "2026-06-10", "serialNo": 10 },
  { "name": "Sharmin Jerin", "fatherName": "Naser Uddin", "motherName": "Jesmin Akter", "address": "Notunpara", "mobile": "01863374176", "course": "Computer Office Application", "roll": "112", "pin": "7417", "regDate": "2026-06-10", "serialNo": 11 },
  { "name": "Hasan Tareq", "fatherName": "Mohammad syed hossaIN", "motherName": "Rashada Akter", "address": "Foteyabad", "mobile": "1994446992", "course": "Computer Office Application", "roll": "113", "pin": "1234", "regDate": "2026-06-10", "serialNo": 12 },
  { "name": "Taohid Tanvir", "fatherName": "Quabi Farid Hyder", "motherName": "Nasira hyder", "address": "Aman Bazar", "mobile": "1812373946", "course": "Computer Office Application", "roll": "114", "pin": "1234", "regDate": "2026-06-10", "serialNo": 13 },
  { "name": "Yasar Bin Faiz", "fatherName": "Faizul Islam Sikder", "motherName": "Jesmin Akter", "address": "aman bazar", "mobile": "01631829762", "course": "Computer Office Application", "roll": "115", "pin": "1234", "regDate": "2026-06-10", "serialNo": 14 },
  { "name": "Ikrar Jahan", "fatherName": "Md yousop", "motherName": "taslima akter", "address": "Aman bazar", "mobile": "01821305317", "course": "Computer Office Application", "roll": "116", "pin": "1234", "regDate": "2026-06-10", "serialNo": 15 },
  { "name": "Md minhaj ahamed fahim", "fatherName": "mintu", "motherName": "rehena begum", "address": "Aman bazar", "mobile": "01824560010", "course": "Computer Office Application", "roll": "117", "pin": "1234", "regDate": "2026-06-10", "serialNo": 16 },
  { "name": "ismot jerin nikita", "fatherName": "abul bashaR", "motherName": "LUTFOR NAHAR", "address": "Aman bazar", "mobile": "01830218417", "course": "Computer Office Application", "roll": "118", "pin": "1234", "regDate": "2026-06-10", "serialNo": 17 },
  { "name": "Meherunnesa joya", "fatherName": "mohammad jamir uddin", "motherName": "khadija yeasmin", "address": "Aman bazar", "mobile": "01311813579", "course": "Computer Office Application", "roll": "119", "pin": "1234", "regDate": "2026-06-10", "serialNo": 18 },
  { "name": "Rehena Akter Ranu", "fatherName": "Md. Osman Goni", "motherName": "Nasima Akter", "address": "Vuliya para", "mobile": "01877918648", "course": "Computer Office Application", "roll": "120", "pin": "1234", "regDate": "2026-06-10", "serialNo": 19 },
  { "name": "Sapana newaz tahiba", "fatherName": "Habib Ullah", "motherName": "Jaheda Akter", "address": "Notun para", "mobile": "01877419244", "course": "Computer Office Application", "roll": "121", "pin": "1234", "regDate": "2026-06-10", "serialNo": 20 },
  { "name": "Bibi Fatema happy", "fatherName": "Md idrish", "motherName": "Bibi Khadiza", "address": "Foteyabad", "mobile": "01894108307", "course": "Computer Office Application", "roll": "122", "pin": "1234", "regDate": "2026-06-10", "serialNo": 21 },
  { "name": "Tasnim Akter", "fatherName": "Bahadur Alam", "motherName": "Yasmin Akter", "address": "Foteyabad", "mobile": "01617788376", "course": "Computer Office Application", "roll": "123", "pin": "1234", "regDate": "2026-06-10", "serialNo": 22 },
  { "name": "Noman Uddin Tareq", "fatherName": "Abul Bashar", "motherName": "Rosha Akter", "address": "Shikarpur", "mobile": "01881126795", "course": "Computer Office Application", "roll": "124", "pin": "1234", "regDate": "2026-06-10", "serialNo": 23 },
  { "name": "Md Nayem Uddin", "fatherName": "Md Nizam Uddin", "motherName": "Jesia Sharif Dilu", "address": "Aman bazar", "mobile": "01882694138", "course": "Computer Office Application", "roll": "125", "pin": "1234", "regDate": "2026-06-10", "serialNo": 24 },
  { "name": "Papon Pal", "fatherName": "Ashutos Pal", "motherName": "Dilu Pal", "address": "Shikarpur", "mobile": "01861210597", "course": "Computer Office Application", "roll": "126", "pin": "1234", "regDate": "2026-06-10", "serialNo": 25 },
  { "name": "Mohammad Emon", "fatherName": "Md Farid Meah", "motherName": "Parvin Akther", "address": "Shikarpur", "mobile": "01601034628", "course": "Computer Office Application", "roll": "127", "pin": "1234", "regDate": "2026-06-10", "serialNo": 26 },
  { "name": "Sayed Hossen Fahim", "fatherName": "Mohammad Hossain", "motherName": "Shahanaz Begum", "address": "Sub register Bari", "mobile": "01806255435", "course": "Computer Office Application", "roll": "128", "pin": "1234", "regDate": "2026-06-10", "serialNo": 27 },
  { "name": "Farhan Islam", "fatherName": "Md Kamal Hossain", "motherName": "Razia Sultana", "address": "Khosal Shah", "mobile": "01771010201", "course": "Computer Office Application", "roll": "129", "pin": "1234", "regDate": "2026-06-10", "serialNo": 28 },
  { "name": "Md Jaber Jonaed", "fatherName": "Md Abdus Salam", "motherName": "Shamsur nahar", "address": "Nosrullah Kazi Bari", "mobile": "01815478891", "course": "Computer Office Application", "roll": "130", "pin": "1234", "regDate": "2026-06-10", "serialNo": 29 },
  { "name": "Irfanul Haq", "fatherName": "Anamul Haq", "motherName": "Lucky Akter", "address": "Vuliya Para", "mobile": "01615749042", "course": "Computer Office Application", "roll": "131", "pin": "1234", "regDate": "2026-06-10", "serialNo": 30 },
  { "name": "Shakib Hasan Hridoy", "fatherName": "Md Anwar Hossain", "motherName": "Ms Halima Begum", "address": "Cantonment", "mobile": "01304330300", "course": "Computer Office Application", "roll": "132", "pin": "1234", "regDate": "2026-06-10", "serialNo": 31 },
  { "name": "Hasibul Islam Ontor", "fatherName": "Md Anwar Hossain", "motherName": "Ms Halima Begum", "address": "Cantonment", "mobile": "01318798163", "course": "Computer Office Application", "roll": "133", "pin": "1234", "regDate": "2026-06-10", "serialNo": 32 },
  { "name": "Harunur Rashid", "fatherName": "Md Abdul Mannan", "motherName": "NurnaharBegum", "address": "Aman Bazar", "mobile": "01836553630", "course": "Computer Office Application", "roll": "134", "pin": "1234", "regDate": "2026-06-10", "serialNo": 33 },
  { "name": "Shahed ul Islam", "fatherName": "Jamal Uddin", "motherName": "Roma Akter", "address": "Abdul roshid Bari", "mobile": "01941942704", "course": "Computer Office Application", "roll": "135", "pin": "1234", "regDate": "2026-06-10", "serialNo": 34 },
  { "name": "Saidul islam Afif", "fatherName": "Md Rafique", "motherName": "Rehana Akter", "address": "Zugirhat", "mobile": "01710845370", "course": "Computer Office Application", "roll": "136", "pin": "1234", "regDate": "2026-06-10", "serialNo": 35 },
  { "name": "Ajmain Khan", "fatherName": "Saifuffin Khan", "motherName": "Muna Khanam", "address": "Aman Bazar", "mobile": "01829977777", "course": "Computer Office Application", "roll": "137", "pin": "1234", "regDate": "2026-06-10", "serialNo": 36 },
  { "name": "Tanzibul Islam", "fatherName": "Zahedul islam", "motherName": "Jannatul Naiyen", "address": "Aman Bazar", "mobile": "01754025417", "course": "Computer Office Application", "roll": "138", "pin": "1234", "regDate": "2026-06-10", "serialNo": 37 },
  { "name": "Mohammad Jayedul Hasan", "fatherName": "Md jalal uddin", "motherName": "Shanaj Begum", "address": "Juhgir Hat", "mobile": "01828146802", "course": "Computer Office Application", "roll": "139", "pin": "1234", "regDate": "2026-06-10", "serialNo": 38 },
  { "name": "Onik Mutsuddi", "fatherName": "Monojit Mutsuddi", "motherName": "Purnima Mutsuddi", "address": "Aman Bazar", "mobile": "01610235434", "course": "Computer Office Application", "roll": "140", "pin": "1234", "regDate": "2026-06-10", "serialNo": 39 },
  { "name": "Md Rayhan", "fatherName": "Md Lokman", "motherName": "MMomena Begum", "address": "Aman Bazar", "mobile": "01325871562", "course": "Computer Office Application", "roll": "141", "pin": "1234", "regDate": "2026-06-10", "serialNo": 40 },
  { "name": "Abu Obayda", "fatherName": "MD Nasir", "motherName": "Saheda sultana", "address": "Fokir para", "mobile": "01882679001", "course": "Computer Office Application", "roll": "142", "pin": "1234", "regDate": "2026-06-10", "serialNo": 41 },
  { "name": "Touhidul Islam Abir", "fatherName": "Abu Taher", "motherName": "Nasima Akter", "address": "Asraf alir Bari", "mobile": "01870406514", "course": "Computer Office Application", "roll": "143", "pin": "1234", "regDate": "2026-06-10", "serialNo": 42 },
  { "name": "Sayed khan rahat", "fatherName": "Shamsul alom", "motherName": "Josna akter", "address": "Jugirhat", "mobile": "018xxxxxxx", "course": "Computer Office Application", "roll": "144", "pin": "1234", "regDate": "2026-06-10", "serialNo": 43 },
  { "name": "Hosen Al Jaber", "fatherName": "Jakir Hose", "motherName": "Nilu Akter", "address": "Jugirhat", "mobile": "01863350746", "course": "Computer Office Application", "roll": "145", "pin": "1234", "regDate": "2026-06-10", "serialNo": 44 },
  { "name": "Mahfuj Ahmed", "fatherName": "Monir Ahamed", "motherName": "Sharmin akter", "address": "Aman Bazar", "mobile": "01896093213", "course": "Computer Office Application", "roll": "146", "pin": "1234", "regDate": "2026-06-10", "serialNo": 45 },
  { "name": "Md arafat", "fatherName": "Mohammad Sarowar", "motherName": "Asma begum", "address": "SIKABPUR", "mobile": "01819162236", "course": "Computer Office Application", "roll": "147", "pin": "1234", "regDate": "2026-06-10", "serialNo": 46 },
  { "name": "Jinuh Marma", "fatherName": "#", "motherName": "#", "address": "Borodigirpar", "mobile": "01619755108", "course": "Computer Office Application", "roll": "148", "pin": "1234", "regDate": "2026-06-10", "serialNo": 47 },
  { "name": "Md shakil", "fatherName": "Abdus salam", "motherName": "Mst Shanaj", "address": "Cantonment", "mobile": "01805058414", "course": "Computer Office Application", "roll": "149", "pin": "1234", "regDate": "2026-06-10", "serialNo": 48 },
  { "name": "Sanjida Nur jerin", "fatherName": "Muhammad Nur Nobi", "motherName": "Ruzi Akther", "address": "Zugirhat", "mobile": "01793044702", "course": "Computer Office Application", "roll": "150", "pin": "1234", "regDate": "2026-06-10", "serialNo": 49 },
  { "name": "Nusrat Jahan", "fatherName": "Asraf Hosen", "motherName": "Farhana Kanom", "address": "Aman Bazar", "mobile": "01617261259", "course": "Computer Office Application", "roll": "151", "pin": "1234", "regDate": "2026-06-10", "serialNo": 50 },
  { "name": "Kakoli Das", "fatherName": "Mintu Das", "motherName": "Purnima Das", "address": "Aman Bazar", "mobile": "01834792118", "course": "Computer Office Application", "roll": "152", "pin": "1234", "regDate": "2026-06-10", "serialNo": 51 },
  { "name": "Asaduzzaman Rifat", "fatherName": "Ayub khan", "motherName": "Ferdus Begum", "address": "Aman bazar", "mobile": "01861857505", "course": "Computer Office Application", "roll": "153", "pin": "1234", "regDate": "2026-06-10", "serialNo": 52 },
  { "name": "anjan dev nath", "fatherName": "Sapan kumar Dev nath", "motherName": "Nrva rani debi", "address": "Aman bazar", "mobile": "01861141277", "course": "Computer Office Application", "roll": "154", "pin": "1234", "regDate": "2026-06-10", "serialNo": 53 }
];

export const INITIAL_RESULTS: ModelTestResult[] = [
  {
    roll: "1001",
    name: "Md Minhajul Kabir",
    course: "Computer Office Application",
    mcqMarks: 44,
    practicalMarks: 36,
    vivaMarks: 9,
    total: 89,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "চমৎকার পারফরম্যান্স! আপনার টাইপিং এবং ফর্মুলা স্কিল খুবই ভালো।"
  },
  {
    roll: "1002",
    name: "Nur Islam Babo",
    course: "Computer Office Application",
    mcqMarks: 38,
    practicalMarks: 32,
    vivaMarks: 8,
    total: 78,
    gpaPoint: 4.5,
    gpaGrade: "A",
    remarks: "খুব চমৎকার। এক্সেল ফর্মুলাগুলোতে আরও একটু অনুশীলন করতে হবে।"
  },
  {
    roll: "1003",
    name: "Hamida Sultana",
    course: "Computer Office Application",
    mcqMarks: 46,
    practicalMarks: 38,
    vivaMarks: 10,
    total: 94,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "অসাধারণ ফলাফল! ব্যাচের অন্যতম সেরা মার্কশীট আপনার।"
  },
  {
    roll: "1004",
    name: "Rakibul Hassan",
    course: "Computer Office Application",
    mcqMarks: 42,
    practicalMarks: 35,
    vivaMarks: 8,
    total: 85,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "উত্তীর্ণ হয়েছেন। কম্পিউটার ডক্যুমেন্টেশনে দারুণ সাবলীলতা দেখিয়েছেন।"
  },
  {
    roll: "1005",
    name: "Suprity Shil",
    course: "Graphic Design & Multimedia",
    mcqMarks: 35,
    practicalMarks: 38,
    vivaMarks: 9,
    total: 82,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "ডিজাইন সেন্স অত্যন্ত সুক্ষ্ম ও চমৎকার। কালার সিলেকশন প্রশংসনীয়।"
  },
  {
    roll: "1006",
    name: "Tusha Chowdhury",
    course: "Computer Office Application",
    mcqMarks: 32,
    practicalMarks: 28,
    vivaMarks: 7,
    total: 67,
    gpaPoint: 3.5,
    gpaGrade: "A-",
    remarks: "উত্তীর্ণ হয়েছেন। তবে থিওরি এবং শর্টকাট কি গুলোতে মনোযোগ বাড়াতে হবে।"
  },
  {
    roll: "1007",
    name: "Jubayer Ivna",
    course: "Graphic Design & Multimedia",
    mcqMarks: 36,
    practicalMarks: 34,
    vivaMarks: 8,
    total: 78,
    gpaPoint: 4.5,
    gpaGrade: "A",
    remarks: "ভেক্টর ড্রইং এ দারুণ দক্ষতা দেখিয়েছেন। টাইপ টুল নিয়ে আরও প্র্যাকটিস করুন।"
  },
  {
    roll: "1008",
    name: "Shirin Akter",
    course: "Computer Office Application",
    mcqMarks: 40,
    practicalMarks: 33,
    vivaMarks: 8,
    total: 81,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "অনেক চমৎকার পারফরম্যান্স। স্পিড আরও বাড়ানোর ওপর জোর দিন।"
  },
  {
    roll: "1009",
    name: "Nusrat Alam",
    course: "Computer Office Application",
    mcqMarks: 45,
    practicalMarks: 37,
    vivaMarks: 9,
    total: 91,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "এ প্লাস! থিউরি এবং প্র্যাক্টিক্যাল দুটোতেই অনেক পরিপক্ব।"
  },
  {
    roll: "1010",
    name: "Emon Chowdhury",
    course: "Professional Web Development",
    mcqMarks: 38,
    practicalMarks: 35,
    vivaMarks: 9,
    total: 82,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "রসপোর্ন্সিভ ডিজাইন ও CSS পজিশনিং অত্যন্ত সুন্দরভাবে ফুটিয়ে তুলেছেন।"
  },
  {
    roll: "1011",
    name: "Sharmin Jerin",
    course: "Computer Office Application",
    mcqMarks: 28,
    practicalMarks: 26,
    vivaMarks: 6,
    total: 60,
    gpaPoint: 3.0,
    gpaGrade: "B",
    remarks: "পাস করেছেন। পাওয়ার পয়েন্ট স্লাইড এবং এক্সেল শিটে আরও কঠোর প্র্যাকটিস প্রয়োজন।"
  },
  {
    roll: "1012",
    name: "Hasan Tareq",
    course: "Professional Web Development",
    mcqMarks: 45,
    practicalMarks: 38,
    vivaMarks: 10,
    total: 93,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "চমৎকার কোডিং স্টাইল! কমপ্লেক্স লজিক হ্যান্ডেলিং দক্ষতা অনেক উঁচুমনের।"
  },
  {
    roll: "1013",
    name: "Taohid Tanvir",
    course: "Computer Office Application",
    mcqMarks: 35,
    practicalMarks: 30,
    vivaMarks: 7,
    total: 72,
    gpaPoint: 4.0,
    gpaGrade: "A",
    remarks: "ভালো হয়েছে। নিয়মিত ক্লাসে আসার সুফল পেয়েছেন পরীক্ষায়।"
  },
  {
    roll: "1014",
    name: "Yasar Bin Faiz",
    course: "Database Programming & MS Access",
    mcqMarks: 42,
    practicalMarks: 36,
    vivaMarks: 8,
    total: 86,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "কোয়েরি রিলেশনশিপ এবং ফর্ম ডিজাইন নিখুঁত হয়েছে।"
  },
  {
    roll: "1015",
    name: "Ikrar Jahan",
    course: "Graphic Design & Multimedia",
    mcqMarks: 30,
    practicalMarks: 28,
    vivaMarks: 7,
    total: 65,
    gpaPoint: 3.5,
    gpaGrade: "A-",
    remarks: "পাস করেছেন। ফটোশপ লেয়ার মাস্কিং এবং পেন টুলে আরও মনযোগী হতে হবে।"
  },
  {
    roll: "1016",
    name: "Jannatul Ferdous",
    course: "Computer Office Application",
    mcqMarks: 39,
    practicalMarks: 34,
    vivaMarks: 8,
    total: 81,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "চমৎকার পারফরম্যান্স! টাইপিং ও ডকুমেন্ট ফরম্যাটিং নিখুঁত হয়েছে।"
  },
  {
    roll: "1017",
    name: "Md Sakib Hasan",
    course: "Professional Web Development",
    mcqMarks: 41,
    practicalMarks: 36,
    vivaMarks: 9,
    total: 86,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "এ প্লাস! জাভাস্ক্রিপ্ট কোডিংয়ে অনেক প্রগ্রেস করেছেন।"
  },
  {
    roll: "1018",
    name: "Fatema Tuz Zohra",
    course: "Graphic Design & Multimedia",
    mcqMarks: 35,
    practicalMarks: 32,
    vivaMarks: 8,
    total: 75,
    gpaPoint: 4.5,
    gpaGrade: "A",
    remarks: "খুব ভালো ডিজাইন সেন্স ও কালার থিওরির প্রয়োগ।"
  },
  {
    roll: "1019",
    name: "Monirul Islam",
    course: "Computer Office Application",
    mcqMarks: 36,
    practicalMarks: 32,
    vivaMarks: 8,
    total: 76,
    gpaPoint: 4.5,
    gpaGrade: "A",
    remarks: "উত্তীর্ণ হয়েছেন। এক্সেল ফর্মুলা প্র্যাকটিসে আরো মনযোগী হোন।"
  },
  {
    roll: "1020",
    name: "Tasfia Tabassum",
    course: "Computer Office Application",
    mcqMarks: 43,
    practicalMarks: 37,
    vivaMarks: 9,
    total: 89,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "দুর্দান্ত রেজাল্ট! টাইপিং স্পিডও অনেক প্রশংসনীয়।"
  },
  {
    roll: "1021",
    name: "Kazi Shafiul Alam",
    course: "Database Programming & MS Access",
    mcqMarks: 40,
    practicalMarks: 34,
    vivaMarks: 8,
    total: 82,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "রিলেশনাল ডাটাবেজ ডিজাইনে অসাধারণ দক্ষতা দেখিয়েছেন।"
  },
  {
    roll: "1022",
    name: "Sabrina Yesmin",
    course: "Graphic Design & Multimedia",
    mcqMarks: 38,
    practicalMarks: 35,
    vivaMarks: 8,
    total: 81,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "লোগো ডিজাইন ও ফটো এডিটিং সেশনে দারুণ সাফল্য।"
  },
  {
    roll: "1023",
    name: "Tanjilur Rahman",
    course: "Computer Office Application",
    mcqMarks: 33,
    practicalMarks: 29,
    vivaMarks: 7,
    total: 69,
    gpaPoint: 3.5,
    gpaGrade: "A-",
    remarks: "পাস করেছেন। টাইপিং গতি বাড়াতে আরো পরিশ্রম করুন।"
  },
  {
    roll: "1024",
    name: "Ishrat Jahan Riya",
    course: "Professional Web Development",
    mcqMarks: 45,
    practicalMarks: 37,
    vivaMarks: 9,
    total: 91,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "চমৎকার কোডিং স্টাইল ও রেসপন্সিভ ওয়েব লেআউট।"
  },
  {
    roll: "1025",
    name: "Md Abul Kalam",
    course: "Computer Office Application",
    mcqMarks: 37,
    practicalMarks: 33,
    vivaMarks: 8,
    total: 78,
    gpaPoint: 4.5,
    gpaGrade: "A",
    remarks: "খুব ভালো হয়েছে। নিয়মিত প্র্যাকটিস ধরে রাখুন।"
  },
  {
    roll: "1026",
    name: "Sree Joyonto Nath",
    course: "Computer Office Application",
    mcqMarks: 34,
    practicalMarks: 31,
    vivaMarks: 8,
    total: 73,
    gpaPoint: 4.0,
    gpaGrade: "A",
    remarks: "উত্তীর্ণ হয়েছেন। কম্পিউটার অফিস সেশনে নিয়মিত থাকার ফলাফল।"
  },
  {
    roll: "1027",
    name: "Shahnaj Akter",
    course: "Graphic Design & Multimedia",
    mcqMarks: 42,
    practicalMarks: 35,
    vivaMarks: 9,
    total: 86,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "ডিজাইন পোর্টফোলিও বেশ আকর্ষণীয় ও চমৎকার হয়েছে।"
  },
  {
    roll: "1028",
    name: "Ashraful Islam",
    course: "Computer Office Application",
    mcqMarks: 31,
    practicalMarks: 28,
    vivaMarks: 7,
    total: 66,
    gpaPoint: 3.5,
    gpaGrade: "A-",
    remarks: "পাস করেছেন। ডাটা এন্ট্রি ওয়ার্কে গতি আনতে হবে।"
  },
  {
    roll: "1029",
    name: "Rumana Chowdhury",
    course: "Database Programming & MS Access",
    mcqMarks: 41,
    practicalMarks: 36,
    vivaMarks: 8,
    total: 85,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "অত্যন্ত সূক্ষ্ম কোয়েরি লজিক ও ইন্টারফেস ডিজাইন।"
  },
  {
    roll: "1030",
    name: "Md Arman Khan",
    course: "Professional Web Development",
    mcqMarks: 42,
    practicalMarks: 38,
    vivaMarks: 9,
    total: 89,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "রিয়্যাক্ট হুকস এবং কম্পোনেন্ট আর্কিটেকচার খুব চমৎকার।"
  },
  {
    roll: "1031",
    name: "Afridi Hassan",
    course: "Computer Office Application",
    mcqMarks: 35,
    practicalMarks: 32,
    vivaMarks: 8,
    total: 75,
    gpaPoint: 4.5,
    gpaGrade: "A",
    remarks: "ভালো ফলাফল। এমএস পাওয়ারপয়েন্ট স্লাইডগুলোতে আরো যত্নশীল হোন।"
  },
  {
    roll: "1032",
    name: "Pinky Debnath",
    course: "Computer Office Application",
    mcqMarks: 38,
    practicalMarks: 34,
    vivaMarks: 8,
    total: 80,
    gpaPoint: 5.0,
    gpaGrade: "A+",
    remarks: "অনেক অভিনন্দন! এমএস ওয়ার্ডে চমৎকার বায়োডাটা এবং টেবিল তৈরি করেছেন।"
  }
];

export const GALLERY_IMAGES: any[] = [];
